### ISSUE TITLE
Compilation failure when installing via PIP

### ISSUE THREAD

**Issue by flying-sheep** [PMBio/limix#14]
<details><summary>output</summary>

```c
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/liknorm
    copying liknorm/machine.py -> build/lib.linux-x86_64-3.5/liknorm
    copying liknorm/__init__.py -> build/lib.linux-x86_64-3.5/liknorm
    copying liknorm/_build.py -> build/lib.linux-x86_64-3.5/liknorm
    running egg_info
    writing requirements to liknorm_py.egg-info/requires.txt
    writing liknorm_py.egg-info/PKG-INFO
    writing top-level names to liknorm_py.egg-info/top_level.txt
    writing dependency_links to liknorm_py.egg-info/dependency_links.txt
    reading manifest file 'liknorm_py.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'liknorm_py.egg-info/SOURCES.txt'
    creating build/lib.linux-x86_64-3.5/liknorm/test
    copying liknorm/test/test_liknorm.py -> build/lib.linux-x86_64-3.5/liknorm/test
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-3.5/liknorm._ffi.c'
    creating build/temp.linux-x86_64-3.5
    building 'liknorm._ffi' extension
    creating build/temp.linux-x86_64-3.5/build
    creating build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/icb/philipp.angerer/.local/include -I/home/icb/philipp.angerer/.local/include/python3.5m -c build/temp.linux-x86_64-3.5/liknorm._ffi.c -o build/temp.linux-x86_64-3.5/build/temp.linux-x86_64-3.5/liknorm._ffi.o
    build/temp.linux-x86_64-3.5/liknorm._ffi.c:434:33: fatal error: liknorm/liknorm.h: No such file or directory
         #include "liknorm/liknorm.h"
                                     ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

</details

**Comment by flying-sheep** [comment]
whoops, wrong project, this is libknorm-py

**Comment by Horta** [comment]
Sorry about that, we are working on a proper fix of that.

Meanwhile you can do: conda install -c condo-forge liknorm
and then do pip install limix again...

**Comment by flying-sheep** [comment]
np, bugs happen 😄

i moved this over to limix/liknorm-py#1

i don’t use conda, as it constantly results in bugs caused by conflicts with system library versions and conda library versions. since PyPI also provides increasingly many packages in wheel format, the primary advantage of conda (fast install of binary packages) vanishes. therefore i discourage the use of conda and will suggest that people don’t recommend it.

**Comment by Horta** [comment]
No worries =) I just don't know how to easily provided C-only library that python packages depend on, whereas conda is able to.

Another quick fix for this problem without anaconda is via: https://github.com/limix/travis-tools/blob/master/travis/install-liknorm.sh

**Comment by flying-sheep** [comment]
> I just don't know how to easily provided C-only library that python packages depend on, whereas conda is able to.

it’s pretty easy! you can just use [bdist_wheel](https://packaging.python.org/distributing/#platform-wheels) and upload them as usual with `twine upload dist/*`

**Comment by Horta** [comment]
Yes, I can do that, but them I would need to include the liknorm sources files into liknorm-py, therefore creating a duplication of those files (one copy in the liknorm C-library and one copy in the liknorm-py). I would like to avoid that duplication...

Do you know any way to circumvent that?

**Comment by Horta** [comment]
yes... i will try later on to sort this in a better way without conda... thanks for the help =)

**Comment by flying-sheep** [comment]
sure! drop me a line if i can further help with anything

**Comment by flying-sheep** [comment]
local installation btw worked fine:

```bash
git clone https://github.com/limix/liknorm.git
mkdir liknorm/build && cd liknorm/build
cmake -DCMAKE_INSTALL_PREFIX:PATH=$HOME/.local ..
make && make install
```

**Comment by Horta** [comment]
Glad to hear =)
