### ISSUE TITLE
genotype_reader_tables() error

### ISSUE THREAD

**Issue by mforneris** [PMBio/limix#15]
I have recently update my local installation of limix. It is working through Anaconda 2 v. 4.4.0. 
Limix version is: u'0.7.12'

The installation went fine trough conda but when I use genotype_reader_tables() to read an hdf5 genotype (the same file was working with previous version) it gives me this error:

>>> geno_reader  = gr.genotype_reader_tables(geno_file)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/g/furlong/forneris/software/anaconda2/lib/python2.7/site-packages/limix/io/genotype_reader.py", line 236, in __init__
    self.load()
  File "/g/furlong/forneris/software/anaconda2/lib/python2.7/site-packages/limix/io/genotype_reader.py", line 248, in load
    self.f = tables.openFile(self.file_name,'r')
AttributeError: 'module' object has no attribute 'openFile'

**Comment by Horta** [comment]
Hi @mforneris . Limix is now on version 1.0.9: https://pypi.python.org/pypi/limix/1.0.9

Have a look at that more recent version. It will probably work better for you...

**Comment by mforneris** [comment]
Thank you for taking care of it.

The update through pip worked and the package is loading properly.

I can see that some function changed their names though :/
For example
And all io packages work only if loaded from limix_legacy and not from limix
genotype_reader_tables now is genotype_reader_h5py

This is quiet annoying because is going to break all my scripts…
Is there any chance you will develop “backward compatibility" for the old functions? Can I return to an older limix version?

M.

**Comment by Horta** [comment]
Sorry to hear that. Limix 1.x is a major release and as such breaks some functionalities. However, there will always be the limix_legacy package (pip install limix-legacy) for old functionalities, or you can specify an older limix version to install: pip install limix=0.7.0 for example...
