### ISSUE TITLE
No module named 'mtset'

### ISSUE THREAD

**Issue by samfux84** [PMBio/limix#24]
I tried to install limix from source. I have installed the dependencies manually (pandas, h5py, swig). Then the installation of limix seemed to work without problems. When I tried to import the package, I got an error message about a missing module 'mtset'. Therefore I installed the mtSet module from the git repository (https://github.com/PMBio/mtSet.git), but I still get the same error message:

```
[sfux@euler02 ~]$ module load gcc/4.8.2 gdc python/3.4.3 swig/3.0.8 hdf5/1.8.12          
Autoloading openblas/0.2.13_seq
[sfux@euler02 ~]$ python
Python 3.4.3 (default, Mar  3 2016, 14:52:31) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import limix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cluster/apps/gdc/python/3.4.3/lib64/python3.4/site-packages/limix-0.7.74-py3.4-linux-x86_64.egg/limix/__init__.py", line 2, in <module>
    from .mtSet import MTSet
  File "/cluster/apps/gdc/python/3.4.3/lib64/python3.4/site-packages/limix-0.7.74-py3.4-linux-x86_64.egg/limix/mtSet/__init__.py", line 1, in <module>
    from mtset import MTSet
ImportError: No module named 'mtset'
```

I was a bit surprised, because importing 'mtSet' works without giving an error message:

```
>>> import mtSet
>>> 
```

How can I get limix running ? All the required modules are installed. Is it a typo in the limix module that it tries to import 'mtset' instead of 'mtSet' ?

Thank you very much for your help

**Comment by Horta** [comment]
Hi samfux84. Thank you for the feedback!

The trouble is that limix does not support Python 3 and you are running it with Python 3.4. A quick "fix" would be to run it on Python 2.7. I will have a look at the difficult to port it to Python 3 though.

Let me know how it goes. Thanks!

**Comment by Horta** [comment]
Hi samfux84. I just ported Limix to work on Python 3.4 as well. The Limix from the master branch should work in your environment (if not, please, let us know).

The proper release (on pypi, conda, and github) will have version 0.8.* and should be ready in 2 hours time.

**Comment by samfux84** [comment]
Hi Danilo Horta,

thank you very much vor adding Python 3 support that quickly. I am sorry, I was not aware that the limix package did not support Python 3 before. I am the application specialist of the HPC cluster of ETH Zurich and got a request from one of our users that asked me explicitly to install the package for Python 3.4.3.

Best regards and thank you again for adding Python 3 support.

Sam
