### ISSUE TITLE
setup.py doens't honor standard python setup.py options

### ISSUE THREAD

**Issue by pforai** [PMBio/limix#4]
When trying to run `python setup.py` with `--prefix=foo` the `--prefix` string is passed to SCons which doesn't work as SCons returns with:
`SCons Error: no such option: --prefix`.

**Comment by ink1** [comment]
Confirmed using version 0.6.6 (pypi) and the latest source from the repository.

**Comment by saketkc** [comment]
I made a PR https://github.com/PMBio/limix/pull/9 for this. But I didn't get any response.
I was able to automate most of the things, IIRC.

**Comment by ink1** [comment]
Thank you but no luck I'm afraid. I pulled your setup.py (and upgraded to scons==2.3.4) but the error persists.

**Comment by ostegle** [comment]
Hi all, 

We hav removed the scons dependency and the installer is now a "standard" setup.py. This should work pretty much all systems now and hopefully resolves this for good.
